package com.example.myrecipeapp.RecipeSearchAPI

data class TotalNutrients(
    val CA: Nutrients,
    val CHOLE: Nutrients,
    val ENERC_KCAL: Nutrients,
    val FAMS: Nutrients,
    val FAPU: Nutrients,
    val FASAT: Nutrients,
    val FAT: Nutrients,
    val FATRN: Nutrients,
    val FE: Nutrients,
    val FIBTG: Nutrients,
    val FOLAC: Nutrients,
    val FOLDFE: Nutrients,
    val FOLFD: Nutrients,
    val K: Nutrients,
    val MG: Nutrients,
    val NA: Nutrients,
    val NIA: Nutrients,
    val P: Nutrients,
    val PROCNT: Nutrients,
    val RIBF: Nutrients,
    val SUGAR: Nutrients,
    val SUGARAdded: Nutrients,
    val THIA: Nutrients,
    val TOCPHA: Nutrients,
    val VITA_RAE: Nutrients,
    val VITB12: Nutrients,
    val VITB6A: Nutrients,
    val VITC: Nutrients,
    val VITD: Nutrients,
    val VITK1: Nutrients,
    val WATER: Nutrients,
    val ZN: Nutrients
)